//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by winchen.rc
//
#define IDB_LARGE_EMPTY_B               101
#define IDB_LARGE_EMPTY_W               102
#define IDB_O_BB_B                      103
#define IDB_O_BB_W                      104
#define IDB_O_BK_B                      105
#define IDB_O_BK_W                      106
#define IDB_O_BN_B                      107
#define IDB_O_BN_W                      108
#define IDB_O_BP_B                      109
#define IDB_O_BP_W                      110
#define IDB_O_BQ_B                      111
#define IDB_O_BQ_W                      112
#define IDB_O_BR_B                      113
#define IDB_O_BR_W                      114
#define IDB_SMALL_EMPTY_B               115
#define IDB_SMALL_EMPTY_W               116
#define IDB_O_WB_B                      117
#define IDB_O_WB_W                      118
#define IDB_O_WK_B                      119
#define IDB_O_WK_W                      120
#define IDB_O_WN_B                      121
#define IDB_O_WN_W                      122
#define IDB_O_WP_B                      123
#define IDB_O_WP_W                      124
#define IDB_O_WQ_B                      125
#define IDB_O_WQ_W                      126
#define IDB_O_WR_B                      127
#define IDB_O_WR_W                      128
#define IDB_O_X_B                       129
#define IDB_O_X_W                       130
#define IDB_S_BB_B                      131
#define IDB_S_BB_W                      132
#define IDB_S_BK_B                      133
#define IDB_S_BK_W                      134
#define IDB_S_BN_B                      135
#define IDB_S_BN_W                      136
#define IDB_S_BP_B                      137
#define IDB_S_BP_W                      138
#define IDB_S_BQ_B                      139
#define IDB_S_BQ_W                      140
#define IDB_S_BR_B                      141
#define IDB_S_BR_W                      142
#define IDB_S_WB_B                      143
#define IDB_S_WB_W                      144
#define IDB_S_WK_B                      145
#define IDB_S_WK_W                      146
#define IDB_S_WN_B                      147
#define IDB_S_WN_W                      148
#define IDB_S_WP_B                      149
#define IDB_S_WP_W                      150
#define IDB_S_WQ_B                      151
#define IDB_S_WQ_W                      152
#define IDB_S_WR_B                      153
#define IDB_S_WR_W                      154
#define IDB_T_BB_B                      155
#define IDB_T_BB_W                      156
#define IDB_T_BK_B                      157
#define IDB_T_BK_W                      158
#define IDB_T_BN_B                      159
#define IDB_T_BN_W                      160
#define IDB_T_BP_B                      161
#define IDB_T_BP_W                      162
#define IDB_T_BQ_B                      163
#define IDB_T_BQ_W                      164
#define IDB_T_BR_B                      165
#define IDB_T_BR_W                      166
#define IDB_T_WB_B                      167
#define IDB_T_WB_W                      168
#define IDB_T_WK_B                      169
#define IDB_T_WK_W                      170
#define IDB_T_WN_B                      171
#define IDB_T_WN_W                      172
#define IDB_T_WP_B                      173
#define IDB_T_WP_W                      174
#define IDB_T_WQ_B                      175
#define IDB_T_WQ_W                      176
#define IDB_T_WR_B                      177
#define IDB_T_WR_W                      178
#define IDB_T_X_B                       179
#define IDB_T_X_W                       180
#define TB_W_PIPE_NAME                  1002
#define TB_B_PIPE_NAME                  1003
#define IDC_CHECK_BLUNDER_ALERT_WHITE   1004
#define IDC_CHECK_BLUNDER_ALERT_BLACK   1005
#define IDC_EDIT_EMPTY                  1012
#define IDC_EDIT_WHITE                  1013
#define IDC_EDIT_BLACK                  1014
#define IDC_EDIT_PAWN                   1015
#define IDC_EDIT_KNIGHT                 1016
#define IDC_EDIT_BISHOP                 1017
#define IDC_EDIT_ROOK                   1018
#define IDC_EDIT_QUEEN                  1019
#define IDC_EDIT_KING                   1020
#define IDC_EDIT_WHITE_TIME             1021
#define IDC_EDIT_BLACK_TIME             1022
#define IDC_CHESS_CLIENT                1027
#define IDC_REMOTE_IP                   1028
#define IDC_EDIT_SUGGEST_TIME           1029
#define IDC_CHECK_DING_AFTER_SUGGEST    1030
#define IDC_EDIT_BLUNDER_THRESHOLD      1031
#define ID_GAME_OPPTIME                 40001
#define ID_CHENARD_FILE_EXIT            40002
#define ID_EDIT_CLEARBOARD              40003
#define ID_EDIT_EDITMODE                40004
#define ID_VIEW_ROTATEBOARD             40005
#define ID_VIEW_FRESHEN                 40006
#define ID_VIEW_DEBUGINFO               40007
#define ID_HELP_ABOUT                   40008
#define ID_GAME_FORCEMOVE               40009
#define ID_VIEW_SMALLBOARD              40010
#define ID_VIEW_MEDIUMBOARD             40011
#define ID_VIEW_LARGEBOARD              40012
#define ID_EDIT_COPYGAMELISTING         40013
#define ID_CHENARD_FILE_SAVEAS          40016
#define ID_VIEW_PIECESTYLE_ORIGINAL     40020
#define ID_VIEW_PIECESTYLE_TILBURG      40021
#define ID_GAME_TACTICALBENCHMARK       40023
#define ID_EDIT_THINK_TIMES             40024
#define ID_EDIT_UNDOMOVE                40026
#define ID_EDIT_REDOMOVE                40027
#define ID_VIEW_PIECESTYLE_SKAK         40028
#define ID_VIEW_SPEAKMOVESTHROUGHSOUNDCARD 40029
#define ID_HELP_VISITCHENARDWEBPAGE   40030
#define ID_VIEW_ANALYSIS_NONE           40031
#define ID_VIEW_ANALYSIS_BESTPATH       40032
#define ID_VIEW_ANALYSIS_CURRENTPATH    40033
#define ID_GAME_ALLOWCOMPUTERTORESIGN   40034
#define ID_GAME_RESIGN                  40035
#define ID_HIGHLIGHT_MOVE               40036
#define ID_ANIMATE                      40037
#define ID_GAME_AUTO_SINGULAR           40038
#define ID_GAME_ALLOWEXTENDEDSEARCH     40039
#define ID_DUMP_XPOS_TABLE              40040
#define ID_GAME_SUGGEST                 40041
#define ID_HELP_HOWDOICASTLE            40042
#define ID_CHENARD_FILE_NEW             41000
#define ID_CHENARD_FILE_OPEN            41001
#define ID_CHENARD_FILE_SAVE            41002
#define ID_KEY_N                        42002
#define ID_KEY_S                        42003
#define ID_KEY_E                        42004
#define ID_KEY_W                        42005
#define ID_KEY_NW                       42006
#define ID_KEY_SW                       42007
#define ID_KEY_NE                       42008
#define ID_KEY_SE                       42009
#define ID_KEY_CHOOSE                   42010
#define ID_VIEW_ANNOUNCEMATE            42011
#define ID_EDIT_COPY_FEN                42012
#define ID_ENTER_FEN                    42013
#define ID_ALGEBRAIC_A                  42014
#define ID_ALGEBRAIC_B                  42015
#define ID_ALGEBRAIC_C                  42016
#define ID_ALGEBRAIC_D                  42017
#define ID_ALGEBRAIC_E                  42018
#define ID_ALGEBRAIC_F                  42019
#define ID_ALGEBRAIC_G                  42020
#define ID_ALGEBRAIC_H                  42021
#define ID_ALGEBRAIC_1                  42022
#define ID_ALGEBRAIC_2                  42023
#define ID_ALGEBRAIC_3                  42024
#define ID_ALGEBRAIC_4                  42025
#define ID_ALGEBRAIC_5                  42026
#define ID_ALGEBRAIC_6                  42027
#define ID_ALGEBRAIC_7                  42028
#define ID_ALGEBRAIC_8                  42029
#define ID_GAME_SUGGESTAGAIN            42030
#define ID_EDIT_BLUNDER_THRESHOLD       42031

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         42032
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
